In this problem, you need to train a Hopfield network using the attached image. Use the attached training image to train your network and then evaluate its performance employing the attached test image. To this end, you need to complete each cell step by step.

You have to submit the final saved image as well as the completed notebook. 


In [1]:
import numpy as np
import random
import PIL
from PIL import Image
import os
import re
from google.colab.patches import cv2_imshow 

In [2]:
#Convert a matrix to a vector
def mat2vec(x):
    """convert the matrix x to a vector """

    #### Implement your code ###
    tmp1 = x.flatten()
    
    return tmp1

In [3]:
def create_W(x):
    """  Create a square matrix with the same size as the input size.
    Note 1: The weight matrix must be symmetric
    Tip 1: For row i and column j, while i != j, place the value x [i] * x [j] in the weight matrix w [i, j]
    Tip 2: For row i and column j, while i=j, put the value 0 in the weight matrix w [i, j]
    """
    #### Impelement your code ### 
    row = len(x)
    w = np.zeros((row,row))
    x_vector = mat2vec(x)
    for i in range(row):
        for j in range(row):
            if (i == j):
                w[i,j] = 0
            else:
                w[i,j] = x_vector[i] * x_vector[j]

    return w

In [4]:
#Read an image file and convert it to a pattern of the image
def readImg2array(file,size, threshold= 145):
    img = Image.open(file).convert(mode="L")
    img= img.resize(size)
    #img.thumbnail(size,Image.ANTIALIAS)
    imgArray = np.asarray(img,dtype=np.uint8)
    x = np.zeros(imgArray.shape,dtype=np.float)

    """
    Set the value to 1 for each pixel value with the larger than the threshold,
    and Set the value to -1 for each image pixel with a value of 0.

    """
    #### Implement your code ###
    row,col = imgArray.shape
    print(imgArray)
    for i in range(row):
        for j in range(col):
            if(imgArray[i,j] == 0):
                x[i,j] = -1
                
            elif(imgArray[i,j]>threshold):
                x[i,j] = 1

    return x

In [5]:
#Convert a numpy array to an image file like Jpeg
def array2img(data, outFile = None):

    #data is 1 or -1 matrix
    y = np.zeros(data.shape,dtype=np.uint8)
    y[data==1] = 255
    y[data==-1] = 0
    img = Image.fromarray(y,mode="L")
    if outFile is not None:
        img.save(outFile)
    return img

In [6]:
#Update the test input pattern (y_vec) based on the weight matrix
def update(w,y_vec,theta=0.5,time=100):

    """
    Once in a while, select a random number between 0 and the size of the input vector -1.
    Then use the random number line of the weight matrix to multiply internally by the input vector.
    Subtract the result from theta
    If the end result is greater than 0, enter a value of 1 in the input vector, otherwise replace -1.
    """
    #### Impelement your code ###
    rand_top = len(y_vec) - 1
    
    for i in range(time):
        rnd_num = random.randint(0,rand_top)
        inner_multply = np.dot(w[rnd_num,:],y_vec)
        subtraction = theta - inner_multply
        
        if(subtraction > 0):
            y_vec[i] = 1
        else:
            y_vec[i] = -1
            
    return y_vec

In [7]:

def hopfield(train_files, test_files,theta=0.5, time=1000, size=(100,100),threshold=60):

    """
    Using the built-in functions, Do the following steps:
    1- Read the input image and extract its pattern
    2. Convert the obtained pattern into a vector
    3- Make a weight matrix based on the vector of the previous step
    4- Read the test image and extract its pattern
    5- Convert the test pattern into a vector and give it as the input of the update function along with the built-in weight matrix.

    """
    #### Impelement your code ###
    # 1
    image = readImg2array(train_files,size,threshold)
    
    # 2
    image_vector = mat2vec(image)
    
    # 3
    w = create_W(image_vector)
    
    # 4
    tst_image = readImg2array(test_files,size,threshold)
    
    # 5 
    y_vec = mat2vec(tst_image)
    
    oshape = (100,100)
    
    y_vec_after = update(w=w,y_vec=y_vec,theta=theta,time=time)
    y_vec_after = y_vec_after.reshape(oshape)
    after_img = array2img(y_vec_after,outFile=None)
    after_img.save("result.jpg")
    after_img.show()
        

In [8]:
train_files = 'train.jpg'
test_files = 'test.jpg'
hopfield(train_files, test_files, theta=0.5,time=100,size=(100,100),threshold=60)


[[212 225 214 ... 218 213 192]
 [205 217 208 ... 187 193 204]
 [205 209 194 ... 178 186 165]
 ...
 [161 164 181 ... 191 146 156]
 [132 107 100 ... 184 162 148]
 [ 44 119  88 ... 157 163 129]]
[[207 221 208 ... 213 206 182]
 [199 212 200 ... 175 183 195]
 [200 203 185 ... 165 175 151]
 ...
 [143 148 165 ... 181 131 144]
 [115  87  82 ... 174 150 136]
 [ 35 102  71 ... 145 152 115]]
